//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNureRulesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int Id { get; set; }
        public string Term1 { get; set; }
        public string Definition { get; set; }
        public int AdminId { get; set; }
    
        public virtual User User { get; set; }
    }
}
