//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyNureRulesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int Id { get; set; }
        public string Term1 { get; set; }
        public string Definition { get; set; }
        public int AdminId { get; set; }
    
        public virtual User User { get; set; }
    }
}
